Fix bug which causes JSON serialization error
The ``help_text`` is a Django proxy, and without this fix (on
Django==1.4.2, TastyPie==0.9.11) a JSON serialization error is raised::

    TypeError: <django.utils.functional.__proxy__ object at 0x103c09450> is not JSON serializable